// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    About: typeof import('./src/components/pages/About.vue')['default']
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    ArabicKB: typeof import('./src/components/ArabicKB.vue')['default']
    FirdleLogo: typeof import('./src/components/FirdleLogo.vue')['default']
    IIcBaselineKeyboardArrowDown: typeof import('~icons/ic/baseline-keyboard-arrow-down')['default']
    IIcBaselineSettings: typeof import('~icons/ic/baseline-settings')['default']
    Index: typeof import('./src/components/pages/Index.vue')['default']
    KBButton: typeof import('./src/components/KBButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
