// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    About: typeof import('./src/components/pages/About.vue')['default']
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    AppTutorial: typeof import('./src/components/AppTutorial.vue')['default']
    FAppBar: typeof import('./src/components/base/FAppBar.vue')['default']
    FAppBarMini: typeof import('./src/components/base/FAppBarMini.vue')['default']
    FAppBarRegular: typeof import('./src/components/base/FAppBarRegular.vue')['default']
    FButton: typeof import('./src/components/base/FButton.vue')['default']
    FIndicator: typeof import('./src/components/base/FIndicator.vue')['default']
    FirdleLogo: typeof import('./src/components/FirdleLogo.vue')['default']
    FModal: typeof import('./src/components/base/FModal.vue')['default']
    FOverlay: typeof import('./src/components/base/FOverlay.vue')['default']
    FSnackBar: typeof import('./src/components/base/FSnackBar.vue')['default']
    GameCell: typeof import('./src/components/GameCell.vue')['default']
    GameCellHarf: typeof import('./src/components/GameCellHarf.vue')['default']
    GameCellResult: typeof import('./src/components/GameCellResult.vue')['default']
    GameGrid: typeof import('./src/components/GameGrid.vue')['default']
    GameRow: typeof import('./src/components/GameRow.vue')['default']
    IIcBaselineClose: typeof import('~icons/ic/baseline-close')['default']
    IIcBaselineContentCopy: typeof import('~icons/ic/baseline-content-copy')['default']
    IIcBaselineInfo: typeof import('~icons/ic/baseline-info')['default']
    IIcBaselineKeyboardArrowDown: typeof import('~icons/ic/baseline-keyboard-arrow-down')['default']
    IIcBaselineOpenInNew: typeof import('~icons/ic/baseline-open-in-new')['default']
    IIcBaselinePlaylistAddCheck: typeof import('~icons/ic/baseline-playlist-add-check')['default']
    IIcBaselineQuestionMark: typeof import('~icons/ic/baseline-question-mark')['default']
    IIcRoundFormatListBulleted: typeof import('~icons/ic/round-format-list-bulleted')['default']
    Index: typeof import('./src/components/pages/Index.vue')['default']
    InfoBox: typeof import('./src/components/InfoBox.vue')['default']
    IPhSpinnerGapDuotone: typeof import('~icons/ph/spinner-gap-duotone')['default']
    KB: typeof import('./src/components/KB.vue')['default']
    KBButton: typeof import('./src/components/KBButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
