// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    About: typeof import('./src/components/pages/About.vue')['default']
    AppAppBar: typeof import('./src/components/AppAppBar.vue')['default']
    AppBar: typeof import('./src/components/base/AppBar.vue')['default']
    AppBarMini: typeof import('./src/components/base/AppBarMini.vue')['default']
    AppBarRegular: typeof import('./src/components/base/AppBarRegular.vue')['default']
    ArabicKB: typeof import('./src/components/ArabicKB.vue')['default']
    Dialog: typeof import('./src/components/base/Dialog.vue')['default']
    FAppBar: typeof import('./src/components/base/FAppBar.vue')['default']
    FAppBarMini: typeof import('./src/components/base/FAppBarMini.vue')['default']
    FAppBarRegular: typeof import('./src/components/base/FAppBarRegular.vue')['default']
    FIndicator: typeof import('./src/components/base/FIndicator.vue')['default']
    FirdleLogo: typeof import('./src/components/FirdleLogo.vue')['default']
    FModal: typeof import('./src/components/base/FModal.vue')['default']
    FSnackBar: typeof import('./src/components/base/FSnackBar.vue')['default']
    GameCell: typeof import('./src/components/GameCell.vue')['default']
    GameCellHarf: typeof import('./src/components/GameCellHarf.vue')['default']
    GameCellParent: typeof import('./src/components/GameCellParent.vue')['default']
    GameCellResult: typeof import('./src/components/GameCellResult.vue')['default']
    GameGrid: typeof import('./src/components/GameGrid.vue')['default']
    GameRow: typeof import('./src/components/GameRow.vue')['default']
    Grid: typeof import('./src/components/Grid.vue')['default']
    IIcBaselineCheck: typeof import('~icons/ic/baseline-check')['default']
    IIcBaselineClose: typeof import('~icons/ic/baseline-close')['default']
    IIcBaselineInfo: typeof import('~icons/ic/baseline-info')['default']
    IIcBaselineKeyboardArrowDown: typeof import('~icons/ic/baseline-keyboard-arrow-down')['default']
    IIcBaselinePlaylistAddCheck: typeof import('~icons/ic/baseline-playlist-add-check')['default']
    IIcBaselineQuestionMark: typeof import('~icons/ic/baseline-question-mark')['default']
    IIcBaselineSettings: typeof import('~icons/ic/baseline-settings')['default']
    IIcRoundFormatListBulleted: typeof import('~icons/ic/round-format-list-bulleted')['default']
    Index: typeof import('./src/components/pages/Index.vue')['default']
    Indicator: typeof import('./src/components/base/Indicator.vue')['default']
    InfoBox: typeof import('./src/components/InfoBox.vue')['default']
    IPhSpinnerGapDuotone: typeof import('~icons/ph/spinner-gap-duotone')['default']
    KB: typeof import('./src/components/KB.vue')['default']
    KBButton: typeof import('./src/components/KBButton.vue')['default']
    Modal: typeof import('./src/components/base/Modal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SnackBar: typeof import('./src/components/base/SnackBar.vue')['default']
  }
}
