HTTP/1.1 200 OK
Server: nginx
Date: Fri, 04 Nov 2022 01:04:16 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 35
Connection: close
Access-Control-Allow-Origin: http://localhost:5173

{
  "status": "200",
  "count": 1
}
