/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/answer/': {
    get: {
      parameters: {
        query: {
          value: string
        }
      }
      responses: {
        /** Successful Response */
        200: {
          content: {
            'application/json': {
              status?: components['schemas']['def-1']
              data?: components['schemas']['def-3']
            }
          }
        }
      }
    }
  }
  '/fiil/count': {
    get: {
      parameters: {
        query: {
          value: string
        }
      }
      responses: {
        /** Successful Response */
        200: {
          content: {
            'application/json': {
              status?: components['schemas']['def-1']
              data?: components['schemas']['def-0']
            }
          }
        }
      }
    }
  }
  '/fiil/': {
    get: {
      parameters: {
        query: {
          value: string
        }
      }
      responses: {
        /** Successful Response */
        200: {
          content: {
            'application/json': {
              status?: components['schemas']['def-1']
              data?: components['schemas']['def-2']
            }
          }
        }
      }
    }
  }
}

export interface components {
  schemas: {
    /** Count */
    'def-0': {
      count?: number
      value?: string
    }
    /** Status */
    'def-1': {
      /** @enum {number} */
      code?: 200 | 1000
      detail?: string
    }
    /** AlmaanySearch */
    'def-2': {
      matchedResult?: string
      matchedResultHTML?: string
      resultDetails?: string[]
    }
    /** Answer */
    'def-3': {
      answer?: ('matched' | 'misplaced' | 'missed')[]
    }
  }
}

export interface operations {}

export interface external {}
